name: Build GCC for RISC-V

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 1 * *"

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:latest
      options: --platform linux/riscv64
    permissions:
      contents: write

    steps:
      - name: Install dependencies
        run: |
         uname -a
         cat /etc/os-release
         sudo apt-get update
         sudo apt-get install -y \
           build-essential \
           libatomic1 \
           flex \
           bison 
